### ISSUE TITLE
USER STORY: List of Products

### ISSUE THREAD

**Issue by Dee68** [Dee68/booky#5]
As a **User** I can **view list of products** so that **I can purchase**
## Acceptance Criteria
This task will be completed once the products are displayed in their intended location and customers can access them.
## Tasks
- [x] - create products view
- [x] - create a products controller
- [x]  - add sample products to shop frontend
- [x]  - test products are showing up correctly
