### ISSUE TITLE
USER STORY: Registration

### ISSUE THREAD

**Issue by Dee68** [Dee68/booky#7]
As a **User** I can **Create an account** so that **I can view my profile**
## Acceptance Criteria
This task will be completed once a user enters a valid email and a username of 2 to 20 characters as username, then he/she will be sent an email for verification. Also a profile will be created for the registered user.
## Tasks
- [] - create a user model
- [] - create controller
- [] - create view
- [] - create link
- [] - test a user receives a verification email
- [] - test if a user profile is created
